config/routes.rb
Wechat::Application.routes.draw do
  devise_for :users

  resources :message_keywords
  resources :message_auto_reply_musics
  resources :message_auto_reply_texts
  resources :message_auto_reply_news
  resources :message_auto_reply_news_articles
  resources :magento_customers, :only => [:index, :destroy]
  resources :card_logs, :only => [:index]
  resources :message_receives, :only => [:index]
  resources :message_sends, :only => [:index]
  resources :wechat_users, :only => [:index, :edit, :update]
  
  resources :cards, :only => [:index, :show] do
    collection do
      get 'show_code'
      get 'index_byuser'
    end
  end

  

  post 'message_auto_reply_texts/new_model'
  post 'message_auto_reply_texts/destroy'
  post 'message_auto_reply_musics/destroy'
  post 'message_auto_reply_news/destroy'
  
  match 'message_receives' => 'message_receives#index'

  get '/api' => 'api/common#test'
  scope :path => "/api", :via => :post, :defaults => {:format => 'xml'} do
    root :to => 'api/common#echo'
  end

    namespace :the_beast do
      resources :sessions do
        collection do
          get 'success'
        end
      end
    end

  get '/' => 'cards#index' 
  

end

app/models/message_keyword.rb
class MessageKeyword < ActiveRecord::Base
  attr_accessible :content
  has_and_belongs_to_many :message_auto_reply_texts
  has_and_belongs_to_many :message_auto_reply_musics
  has_and_belongs_to_many :message_auto_reply_news
  paginates_per 25
end

app/controllers/message_keywords_controller.rb
# encoding: utf-8
class MessageKeywordsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @message_keywords = params[:key].nil? ? MessageKeyword.page(params[:page]).per(20) : MessageKeyword.where("content like '%#{params[:key]}%'").page(params[:page]).per(20)  
   
  end

  def show
    @message_keyword = MessageKeyword.find(params[:id])
  end

  def new
    @message_keyword = MessageKeyword.new
    @auto_texts = MessageAutoReplyText.all
    @auto_musics = MessageAutoReplyMusic.all
    @auto_news = MessageAutoReplyNews.all
  end

  def edit
    @message_keyword = MessageKeyword.find(params[:id])
    @auto_texts = MessageAutoReplyText.all
    @auto_musics = MessageAutoReplyMusic.all
    @auto_news = MessageAutoReplyNews.all
  end

  def create
    @message_keyword = MessageKeyword.new(params[:message_keyword])
    if !params[:auto_id].nil?
      case params[:auto_type]
      when "text"
        @message_keyword.message_auto_reply_texts << MessageAutoReplyText.find(params[:auto_id])
      when "music"
        @message_keyword.message_auto_reply_musics << MessageAutoReplyMusic.find(params[:auto_id])
      when "news"
        @message_keyword.message_auto_reply_news << MessageAutoReplyNews.find(params[:auto_id])
      end
    end

    if @message_keyword.save
      redirect_to message_keywords_url
    else
      render action: "new" 
    end
  end

  def update
    @message_keyword = MessageKeyword.find(params[:id])

    @message_keyword.message_auto_reply_texts.clear
    @message_keyword.message_auto_reply_musics.clear
    @message_keyword.message_auto_reply_news.clear
    if !params[:auto_id].nil?
      case params[:auto_type]
      when "text"
        @message_keyword.message_auto_reply_texts << MessageAutoReplyText.find(params[:auto_id])
      when "music"
        @message_keyword.message_auto_reply_musics << MessageAutoReplyMusic.find(params[:auto_id])
      when "news"
        @message_keyword.message_auto_reply_news << MessageAutoReplyNews.find(params[:auto_id])
      end
    end

    if @message_keyword.update_attributes(params[:message_keyword])
      redirect_to message_keywords_url
    else
      render action: "edit" 
    end
  end

  def destroy
    @message_keyword = MessageKeyword.find(params[:id])
    @message_keyword.message_auto_reply_texts.destroy_all
    @message_keyword.destroy

    redirect_to message_keywords_url
  end
 
end

app/helpers/message_keywords_helper.rb
module MessageKeywordsHelper
end

app/views/message_keywords/_form.html.erb
<script type="text/javascript">
$.ajaxSetup({
  headers: {
    'X-CSRF-Token': $('meta[name="csrf-token"]').attr('content')
  }
});

function refleshAutoText()
{
  $("#autotext").val('');
}

function addAutoText(textValue)
{
  
  $.ajax({
    url: "/message_auto_reply_texts/new_model",
    type: "POST",
    dataType: "json",
    data: {content:textValue},
    success: function(msg){
      $('#modal-container-text').modal('toggle');
      $("#auto_reply_texts_table").append("<tr><td><input type='radio' name='auto_id' value='"+msg+"' onclick=\"setType('text');\"></td><td>"+textValue+"</td><td><a class='btn btn-link' onclick='destroyAutoText(this,"+msg+")'>destroy</a></td></tr>");
    },
    error: function(XMLHttpRequest, textStatus, errorThrown){
       alert(XMLHttpRequest.responseText)
       alert(textStatus)
    }
  });
}

function destroyAutoText(obj,autotext_id)
{
  $.ajax({
    url: "/message_auto_reply_texts/destroy",
    type: "POST",
    dataType: "json",
    data: {id:autotext_id},
    success: function(msg){
      $(obj).parent().parent().remove();
    }
  });
}

function destroyAutoMusics(obj,automusic_id)
{
  $.ajax({
    url: "/message_auto_reply_musics/destroy",
    type: "POST",
    dataType: "json",
    data: {id:automusic_id},
    success: function(msg){
      $(obj).parent().parent().remove();
    }
  });
}

function destroyAutoNews(obj,autonews_id)
{
  $.ajax({
    url: "/message_auto_reply_news/destroy",
    type: "POST",
    dataType: "json",
    data: {id:autonews_id},
    success: function(msg){
      $(obj).parent().parent().remove();
    }
  });
}

function setType (type) {
  $("#auto_type").val(type);
}

function showNews (news_id)
{
  window.open ('/message_auto_reply_news/'+news_id,'newwindow','height=800,width=600,top=0,left=0,toolbar=no,menubar=no,scrollbars=no, resizable=no,location=no, status=no') 
}
</script>


  <div class="row-fluid">
  <%= form_for(@message_keyword) do |f| %>
  <input type="hidden" name="auto_type" id="auto_type" > 
    <fieldset>
      <div class="span6">
          <legend>关键字</legend> 
      <label>关键字内容:</label><%= f.text_field :content %>
      </div>
      <div class="span6">
          <legend>回复消息</legend> 
      <div class="tabbable" id="tabs-697398">
        <ul class="nav nav-tabs">
          <li class="active">
            <a href="#panel-text" data-toggle="tab">文本</a>
          </li>
          <li>
            <a href="#panel-music" data-toggle="tab">声音</a>
          </li>
          <li>
            <a href="#panel-news" data-toggle="tab">图文</a>
          </li>
        </ul>
        <div class="tab-content">
          <div class="tab-pane active" id="panel-text">
             <a id="modal-text" href="#modal-container-text" role="button" class="btn" data-toggle="modal" onclick="refleshAutoText();">新建文本消息</a>
          
            <div id="modal-container-text" class="modal hide fade" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
             
              <div class="modal-header">
                 <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <h3 id="myModalLabel">
                  文本消息回复
                </h3>
              </div>
              <div class="modal-body">
                <p>
                  <input type="text" id="autotext">
                </p>
              </div>
              <div class="modal-footer">
                 <button class="btn" data-dismiss="modal" aria-hidden="true">关闭</button> <a class="btn btn-primary" onclick="addAutoText($('#autotext').val());">保存设置</a>
              </div>
            </div>
            <table id="auto_reply_texts_table" class="table table-hover">
              <thead>
                <tr>
                  <th>
                    勾选
                  </th>
                  <th>
                    文本内容
                  </th>
                  <th>
                    操作
                  </th>
                </tr>
              </thead>
              <tbody>
                <% @auto_texts.each do | auto_text | %>
                  <tr>
                    <td><input type="radio" name="auto_id" <%= @message_keyword.message_auto_reply_texts.pluck(:id).include?(auto_text.id) ? "checked" : "" %> value="<%=auto_text.id%>" onclick="setType('text');"></td>
                    <td><%=auto_text.content%></td>     
                    <td><a class='btn btn-link' onclick="destroyAutoText(this,<%=auto_text.id%>)">destroy</a></td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
          <div class="tab-pane" id="panel-music">
            <table id="auto_reply_musics_table" class="table table-hover">
                <thead>
                  <tr>
                    <th>
                      勾选
                    </th>
                    <th>
                      文件
                    </th>
                    <th>
                      操作
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <% @auto_musics.each do | auto_music | %>
                    <tr>
                      <td><input type="radio" name="auto_id" <%= @message_keyword.message_auto_reply_musics.pluck(:id).include?(auto_music.id) ? "checked" : "" %>  value="<%=auto_music.id%>" onclick="setType('music');"></td>
                      <td><%=auto_music.music_url%></td>      
                        <td><a class='btn btn-link' onclick="destroyAutoMusics(this,<%=auto_music.id%>)">destroy</a></td>
                    </tr>
                  <% end %>
                </tbody>
            </table>
          </div>
          <div class="tab-pane" id="panel-news">
            <table id="auto_reply_news_table" class="table table-hover">
                <thead>
                  <tr>
                    <th>
                      勾选
                    </th>
                    <th>
                      文件
                    </th>
                    <th>
                      操作
                    </th>
                  </tr>
                </thead>
                <tbody>
                  <% @auto_news.each do | auto_reply_news | %>
                    <tr>
                      <td><input type="radio" name="auto_id" <%= @message_keyword.message_auto_reply_news.pluck(:id).include?(auto_reply_news.id) ? "checked" : "" %>  value="<%=auto_reply_news.id%>" onclick="setType('news');"></td>
                      <td><%=auto_reply_news.content%></td>     
                        <td><a class='btn btn-link' onclick="destroyAutoNews(this,<%=auto_reply_news.id%>)">destroy</a>
                          <a class='btn btn-link' onclick="showNews(<%=auto_reply_news.id%>)">show</a>
                        </td>
                    </tr>
                  <% end %>
                </tbody>
            </table>
          </div>
        </div>
      </div>
      </div>
    </fieldset>
    <%= f.submit :class => "btn", :value => "保存" %>
    <% end %>
    <%= link_to 'Back', message_keywords_path %>
  </div>

app/views/message_keywords/edit.html.erb
<div class="container">
<div >
  <h3>编辑关键字</h3>
</div>
<%= render 'form' %>
</div>

app/views/message_keywords/index.html.erb
<div class="well">
  <h3>关键字列表</h3>
</div>
<div>
<form action="/message_keywords" method="get">
  <input type="input" name="key" /> 
  <input type="submit" value="查询" class="btn" />  </form>
</div>
<%= link_to '新建关键字', new_message_keyword_path, :class => "btn btn-primar" %>
<table class="table table-striped">
  <thead>
    <tr>
    <th>关键字</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @message_keywords.each do |message_keyword| %>
  <tr>
    <td><%=message_keyword.content %></td>
    <td><%= link_to 'Show', message_keyword %></td>
    <td><%= link_to 'Edit', edit_message_keyword_path(message_keyword) %></td>
    <td><%= link_to 'Destroy', message_keyword, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>

<%= paginate @message_keywords %>

app/views/message_keywords/new.html.erb
<div class="container">
<div >
  <h3>新建关键字</h3>
</div>
<%= render 'form' %>
</div>

app/views/message_keywords/show.html.erb
<label>内容</label>
<%= @message_keyword.content %>

<% if @message_keyword.message_auto_reply_texts.size != 0 %>
	<label>文本消息:</label><label><%=@message_keyword.message_auto_reply_texts.first.content %></label>
<% end %>
<% if @message_keyword.message_auto_reply_musics.size != 0 %>
	<label>音乐消息:</label><label><%=@message_keyword.message_auto_reply_musics.first.music_url %></label>
<% end %>
<% if @message_keyword.message_auto_reply_news.size != 0 %>
	<label>图文消息:</label>
	<% @message_keyword.message_auto_reply_news.first.message_auto_reply_news_articles.each do |article|%>
		<label>标题：</label><label><%=article.title %></label></p>
		<label>图片：</label><label><%=article.pic_url %></label></p>
		<label>链接：</label><label><%=article.url %></label></p>
		<label>内容：</label><label><%=article.description %></label></p>
	<% end %>
<% end %>

<%= link_to 'Edit', edit_message_keyword_path(@message_keyword) %> |
<%= link_to 'Back', message_keywords_path %>