config/routes.rb
Wechat::Application.routes.draw do
  devise_for :users

  resources :message_keywords
  resources :message_auto_reply_musics
  resources :message_auto_reply_texts
  resources :message_auto_reply_news
  resources :message_auto_reply_news_articles
  resources :magento_customers, :only => [:index, :destroy]
  resources :card_logs, :only => [:index]
  resources :message_receives, :only => [:index]
  resources :message_sends, :only => [:index]
  resources :wechat_users, :only => [:index, :edit, :update]
  
  resources :cards, :only => [:index, :show] do
    collection do
      get 'show_code'
      get 'index_byuser'
    end
  end

  

  post 'message_auto_reply_texts/new_model'
  post 'message_auto_reply_texts/destroy'
  post 'message_auto_reply_musics/destroy'
  post 'message_auto_reply_news/destroy'
  
  match 'message_receives' => 'message_receives#index'

  get '/api' => 'api/common#test'
  scope :path => "/api", :via => :post, :defaults => {:format => 'xml'} do
    root :to => 'api/common#echo'
  end

    namespace :the_beast do
      resources :sessions do
        collection do
          get 'success'
        end
      end
    end

  get '/' => 'cards#index' 
  

end

app/models/message_auto_reply_music.rb
class MessageAutoReplyMusic < ActiveRecord::Base
  attr_accessible :hq_music_url, :music_url, :title, :description
  has_and_belongs_to_many :message_keywords


  has_attached_file :music_url,  
                    :url  => "/musicfile/:attachment/:id/:style/:filename",
                    :path => ":rails_root/public/musicfile/:attachment/:id/:style/:filename"

  has_attached_file :hq_music_url,  
                    :url  => "/hqmusicfile/:attachment/:id/:style/:filename",
                    :path => ":rails_root/public/hqmusicfile/:attachment/:id/:style/:filename"

end

app/controllers/message_auto_reply_musics_controller.rb
class MessageAutoReplyMusicsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @message_auto_reply_musics = MessageAutoReplyMusic.page(params[:page]).per(20)
  end

  def show
    @message_auto_reply_music = MessageAutoReplyMusic.find(params[:id])
  end

  def new
    @message_auto_reply_music = MessageAutoReplyMusic.new
    @keywords = MessageKeyword.all
  end

  def edit
    @message_auto_reply_music = MessageAutoReplyMusic.find(params[:id])
    @keywords = MessageKeyword.all
  end

  def create
    @message_auto_reply_music = MessageAutoReplyMusic.new(params[:message_auto_reply_music])

    unless params[:keywords].nil?
      params[:keywords].each do |kid|
        @message_auto_reply_music.message_keywords << MessageKeyword.find(kid)
      end
    end
    

    if @message_auto_reply_music.save
      redirect_to @message_auto_reply_music
    else
      render action: "new"
    end
    
  end

  def update
    @message_auto_reply_music = MessageAutoReplyMusic.find(params[:id])


    MessageKeyword.all.each do |mk|
      if params[:keywords].include?(mk.id.to_s) && !@message_auto_reply_music.message_keywords.pluck(:id).include?(mk.id)
        @message_auto_reply_music.message_keywords << mk
      end

      if !params[:keywords].include?(mk.id.to_s) && @message_auto_reply_music.message_keywords.pluck(:id).include?(mk.id)
        @message_auto_reply_music.message_keywords.delete(mk)
      end
    end

    if @message_auto_reply_music.update_attributes(params[:message_auto_reply_music])
      redirect_to @message_auto_reply_music
    else
      render action: "edit"
    end
    
  end

  def destroy
    @message_auto_reply_music = MessageAutoReplyMusic.find(params[:id])
    @message_auto_reply_music.destroy

    redirect_to message_auto_reply_musics_url 
    
  end
end

app/helpers/message_auto_reply_musics_helper.rb
module MessageAutoReplyMusicsHelper
end

app/views/message_auto_reply_musics/_form.html.erb
<div class="row-fluid">
    <div class="span12">
      <%= form_for(@message_auto_reply_music) do |f| %>
        <fieldset>
           <legend>音乐消息</legend>

           <label>标题:</label><%= f.text_field :title %>
           <label>描述:</label><%= f.text_field :description %>
           <label>音乐文件:</label><%= f.file_field :music_url %>
           <label>高质量音乐文件:</label><%= f.file_field :hq_music_url %>
            <div >
              <label>对应关键字: </label>
              <% @keywords.each do |key| %>
                <input type="checkbox" name="keywords[]" value="<%=key.id%>" <%= @message_auto_reply_music.message_keywords.pluck(:id).include?(key.id) ? "checked" : "" %> /><%= key.content %> 
              <% end %>
            </div>
    
           <%= f.submit :class => "btn", :value => "保存" %>

        </fieldset>
      <% end %>
    </div>
</div>

app/views/message_auto_reply_musics/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @message_auto_reply_music %> |
<%= link_to 'Back', message_auto_reply_musics_path %>

app/views/message_auto_reply_musics/index.html.erb
<div class="well">
  <h3>音乐消息列表</h3>
</div>
<%= link_to '新建音乐消息回复', new_message_auto_reply_music_path, :class => "btn btn-primar" %>
<table class="table table-striped">
  <thead>
    <tr>
    <th>title</th>
    <th>description</th>
    <th>URL</th>
    <th>HQ_URL</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<tbody>
<% @message_auto_reply_musics.each do |message_auto_reply_music| %>
  <tr>
    <td><%= message_auto_reply_music.title %></td>
    <td><%= message_auto_reply_music.description %></td>
    <td><a href="<%= message_auto_reply_music.music_url %>" ><%= message_auto_reply_music.music_url %></td>
    <td><a href="<%= message_auto_reply_music.hq_music_url %>" ><%= message_auto_reply_music.hq_music_url %></td>
    <td><%= link_to 'Show', message_auto_reply_music %></td>
    <td><%= link_to 'Edit', edit_message_auto_reply_music_path(message_auto_reply_music) %></td>
    <td><%= link_to 'Destroy', message_auto_reply_music, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>
<%= paginate @message_auto_reply_musics %>

app/views/message_auto_reply_musics/new.html.erb
<%= render 'form' %>

<%= link_to 'Back', message_auto_reply_musics_path %>

app/views/message_auto_reply_musics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>music_url:</b>
  <%= @message_auto_reply_music.music_url %>
</p>

<p>
  <b>hq_music_url:</b>
  <%= @message_auto_reply_music.hq_music_url %>
</p>

<%= link_to 'Edit', edit_message_auto_reply_music_path(@message_auto_reply_music) %> |
<%= link_to 'Back', message_auto_reply_musics_path %>