config/routes.rb
Wechat::Application.routes.draw do
  devise_for :users

  resources :message_keywords
  resources :message_auto_reply_musics
  resources :message_auto_reply_texts
  resources :message_auto_reply_news
  resources :message_auto_reply_news_articles
  resources :magento_customers, :only => [:index, :destroy]
  resources :card_logs, :only => [:index]
  resources :message_receives, :only => [:index]
  resources :message_sends, :only => [:index]
  resources :wechat_users, :only => [:index, :edit, :update]
  
  resources :cards, :only => [:index, :show] do
    collection do
      get 'show_code'
      get 'index_byuser'
    end
  end

  

  post 'message_auto_reply_texts/new_model'
  post 'message_auto_reply_texts/destroy'
  post 'message_auto_reply_musics/destroy'
  post 'message_auto_reply_news/destroy'
  
  match 'message_receives' => 'message_receives#index'

  get '/api' => 'api/common#test'
  scope :path => "/api", :via => :post, :defaults => {:format => 'xml'} do
    root :to => 'api/common#echo'
  end

    namespace :the_beast do
      resources :sessions do
        collection do
          get 'success'
        end
      end
    end

  get '/' => 'cards#index' 
  

end

app/models/message_auto_reply_text.rb
class MessageAutoReplyText < ActiveRecord::Base
  attr_accessible :content
  has_and_belongs_to_many :message_keywords
end

app/controllers/message_auto_reply_texts_controller.rb
class MessageAutoReplyTextsController < ApplicationController
  before_filter :authenticate_user!
  def index
    @message_auto_reply_texts = MessageAutoReplyText.page(params[:page]).per(20)

  end

  def new_model
    @message_auto_reply_text = MessageAutoReplyText.new
    @message_auto_reply_text.content = params[:content]
    @message_auto_reply_text.save
    render :text => @message_auto_reply_text.id.to_s
  end

  def show
    @message_auto_reply_text = MessageAutoReplyText.find(params[:id])
  end

  def new
    @message_auto_reply_text = MessageAutoReplyText.new
    @keywords = MessageKeyword.all
  end

  def edit
    @message_auto_reply_text = MessageAutoReplyText.find(params[:id])
    @keywords = MessageKeyword.all
  end

  def create
    @message_auto_reply_text = MessageAutoReplyText.new(params[:message_auto_reply_text])

    params[:keywords].each do |kid|
      @message_auto_reply_text.message_keywords << MessageKeyword.find(kid)
    end

    if @message_auto_reply_text.save
      redirect_to @message_auto_reply_text
    else
      render action: "new"
    end
    
  end

  def update
    @message_auto_reply_text = MessageAutoReplyText.find(params[:id])


    MessageKeyword.all.each do |mk|
      if params[:keywords].include?(mk.id.to_s) && !@message_auto_reply_text.message_keywords.pluck(:id).include?(mk.id)
        @message_auto_reply_text.message_keywords << mk
      end

      if !params[:keywords].include?(mk.id.to_s) && @message_auto_reply_text.message_keywords.pluck(:id).include?(mk.id)
        @message_auto_reply_text.message_keywords.delete(mk)
      end
    end

    if @message_auto_reply_text.update_attributes(params[:message_auto_reply_text])
      redirect_to @message_auto_reply_text
    else
      render action: "edit"
    end
    
  end

  def destroy
    @message_auto_reply_text = MessageAutoReplyText.find(params[:id])
    @message_auto_reply_text.destroy
    render :text => "{}"    
  end
end

app/helpers/message_auto_reply_texts_helper.rb
module MessageAutoReplyTextsHelper
end

app/views/message_auto_reply_texts/_form.html.erb
<%= form_for(@message_auto_reply_text) do |f| %>
  <% if @message_auto_reply_text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@message_auto_reply_text.errors.count, "error") %> prohibited this message_auto_reply_text from being saved:</h2>

      <ul>
      <% @message_auto_reply_text.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <% @keywords.each do |key| %>
      <input type="checkbox" name="keywords[]" value="<%=key.id%>" <%= @message_auto_reply_text.message_keywords.pluck(:id).include?(key.id) ? "checked" : "" %> /><%= key.content %> 
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/message_auto_reply_texts/edit.html.erb
<h1>Editing message_auto_reply_text</h1>

<%= render 'form' %>

<%= link_to 'Show', @message_auto_reply_text %> |
<%= link_to 'Back', message_auto_reply_texts_path %>

app/views/message_auto_reply_texts/index.html.erb
<h1>Listing message_auto_reply_texts</h1>

<table>
  <tr>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @message_auto_reply_texts.each do |message_auto_reply_text| %>
  <tr>
    <td><%= message_auto_reply_text.content %></td>
    <td><%= link_to 'Show', message_auto_reply_text %></td>
    <td><%= link_to 'Edit', edit_message_auto_reply_text_path(message_auto_reply_text) %></td>
    <td><%= link_to 'Destroy', message_auto_reply_text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Message auto reply text', new_message_auto_reply_text_path %>
<%= paginate @message_auto_reply_texts %>

app/views/message_auto_reply_texts/new.html.erb
<h1>New message_auto_reply_text</h1>

<%= render 'form' %>

<%= link_to 'Back', message_auto_reply_texts_path %>

app/views/message_auto_reply_texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Content:</b>
  <%= @message_auto_reply_text.content %>
</p>


<%= link_to 'Edit', edit_message_auto_reply_text_path(@message_auto_reply_text) %> |
<%= link_to 'Back', message_auto_reply_texts_path %>