config/routes.rb
Wechat::Application.routes.draw do
  devise_for :users

  resources :message_keywords
  resources :message_auto_reply_musics
  resources :message_auto_reply_texts
  resources :message_auto_reply_news
  resources :message_auto_reply_news_articles
  resources :magento_customers, :only => [:index, :destroy]
  resources :card_logs, :only => [:index]
  resources :message_receives, :only => [:index]
  resources :message_sends, :only => [:index]
  resources :wechat_users, :only => [:index, :edit, :update]
  
  resources :cards, :only => [:index, :show] do
    collection do
      get 'show_code'
      get 'index_byuser'
    end
  end

  

  post 'message_auto_reply_texts/new_model'
  post 'message_auto_reply_texts/destroy'
  post 'message_auto_reply_musics/destroy'
  post 'message_auto_reply_news/destroy'
  
  match 'message_receives' => 'message_receives#index'

  get '/api' => 'api/common#test'
  scope :path => "/api", :via => :post, :defaults => {:format => 'xml'} do
    root :to => 'api/common#echo'
  end

    namespace :the_beast do
      resources :sessions do
        collection do
          get 'success'
        end
      end
    end

  get '/' => 'cards#index' 
  

end

app/models/message_auto_reply_news_article.rb
class MessageAutoReplyNewsArticle < ActiveRecord::Base
  attr_accessible :description, :message_auto_reply_news_id, :pic_url, :title, :url
  belongs_to :message_auto_reply_news

  has_attached_file :pic_url, 
  					:url  => "/newspic/:attachment/:id/:style/:filename",
                    :path => ":rails_root/public/newspic/:attachment/:id/:style/:filename"

  validates_attachment :pic_url,  :content_type => { :content_type => ["image/jpeg", "image/jpg","image/png"] }

end

app/controllers/message_auto_reply_news_articles_controller.rb
class MessageAutoReplyNewsArticlesController < ApplicationController
  before_filter :authenticate_user!
  def index
    @message_auto_reply_news_articles = MessageAutoReplyNewsArticle.page(params[:page]).per(20)

  end

  def show
    @message_auto_reply_news_article = MessageAutoReplyNewsArticle.find(params[:id])
  end

  def new
    @message_auto_reply_news_article = MessageAutoReplyNewsArticle.new
    @keywords = MessageAutoReplyNews.all
  end

  def edit
    @message_auto_reply_news_article = MessageAutoReplyNewsArticle.find(params[:id])
    @keywords = MessageAutoReplyNews.all
  end

  def create
    @message_auto_reply_news_article = MessageAutoReplyNewsArticle.new(params[:message_auto_reply_news_article])

   
    if @message_auto_reply_news_article.save
      redirect_to @message_auto_reply_news_article
    else
      render action: "new"
    end
    
  end

  def update
    @message_auto_reply_news_article = MessageAutoReplyNewsArticle.find(params[:id])


	

    if @message_auto_reply_news_article.update_attributes(params[:message_auto_reply_news_article])
      redirect_to @message_auto_reply_news_article
    else
      render action: "edit"
    end
    
  end

  def destroy
    @message_auto_reply_news_article = MessageAutoReplyNewsArticle.find(params[:id])
    @message_auto_reply_news_article.destroy

    redirect_to message_auto_reply_news_articles_url 
    
  end
end

app/helpers/message_auto_reply_news_articles_helper.rb
module MessageAutoReplyNewsArticlesHelper
end

app/views/message_auto_reply_news_articles/_form.html.erb
<div class="row-fluid">
    <div class="span12">
      <%= form_for(@message_auto_reply_news_article) do |f| %>
        <fieldset>
           <legend>文章</legend>
           <label>标题:</label><%= f.text_field :title %>
           <label>描述:</label><%= f.text_field :description %>
           <label>图片:</label><%= f.file_field :pic_url %>
           <label>链接:</label><%= f.text_field :url %>
           <label>图文:</label><%= f.collection_select  :message_auto_reply_news_id, MessageAutoReplyNews.all, :id, :content%>
           <%= f.submit :class => "btn", :value => "保存" %>

        </fieldset>
      <% end %>
    </div>
</div>

app/views/message_auto_reply_news_articles/edit.html.erb
<h1>Editing message_auto_reply_news_article</h1>

<%= render 'form' %>

<%= link_to 'Show', @message_auto_reply_news_article %> |
<%= link_to 'Back', message_auto_reply_news_articles_path %>

app/views/message_auto_reply_news_articles/index.html.erb
<div class="well">
  <h3>文章列表</h3>
</div>
<%= link_to '新建文章', new_message_auto_reply_news_article_path, :class => "btn btn-primar" %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Content</th>
      <th>title</th>
      <th>desc</th>
      <th>pic_url</th>
      <th>url</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
<tbody>

<% @message_auto_reply_news_articles.each do |message_auto_reply_news_article| %>
  <tr>
    <td><%= message_auto_reply_news_article.title %></td>
    <td><%= message_auto_reply_news_article.description %></td>
    <td><%= message_auto_reply_news_article.pic_url %></td>
    <td><%= message_auto_reply_news_article.url %></td>
    <td><%= link_to 'Show', message_auto_reply_news_article %></td>
    <td><%= link_to 'Edit', edit_message_auto_reply_news_article_path(message_auto_reply_news_article) %></td>
    <td><%= link_to 'Destroy', message_auto_reply_news_article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</tbody>
</table>
<%= paginate @message_auto_reply_news_articles %>

app/views/message_auto_reply_news_articles/new.html.erb
<h1>New message_auto_reply_news_article</h1>

<%= render 'form' %>

<%= link_to 'Back', message_auto_reply_news_articles_path %>

app/views/message_auto_reply_news_articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>title:</b>
  <%= @message_auto_reply_news_article.title %>
</p>
<p>
  <b>desc:</b>
  <%= @message_auto_reply_news_article.description %>
</p>
<p>
  <b>pic_url:</b>
  <%= @message_auto_reply_news_article.pic_url %>
</p>
<p>
  <b>url:</b>
  <%= @message_auto_reply_news_article.url %>
</p>

<%= link_to 'Edit', edit_message_auto_reply_news_article_path(@message_auto_reply_news_article) %> |
<%= link_to 'Back', message_auto_reply_news_articles_path %>